### 1. Implement univariate Linear regression using python. Read the data from a ‘.xlsx’ file and save the results to the file. Save the loss at every epoch and plot the graph for the same (Gradient descent). Experiment with polynomial regression with the same data towards nonlinear fit.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import math, copy
import sys
# from sklearn.metrics import mean_absolute_error

In [ ]:
house_model = pd.read_excel("/content/drive/MyDrive/MLassignment/House_Rent_Dataset.xlsx")

In [ ]:
house_model.describe()

               BHK          Rent         Size     Bathroom
count  4746.000000  4.746000e+03  4746.000000  4746.000000
mean      2.083860  3.499345e+04   967.490729     1.965866
std       0.832256  7.810641e+04   634.202328     0.884532
min       1.000000  1.200000e+03    10.000000     1.000000
25%       2.000000  1.000000e+04   550.000000     1.000000
50%       2.000000  1.600000e+04   850.000000     2.000000
75%       3.000000  3.300000e+04  1200.000000     2.000000
max       6.000000  3.500000e+06  8000.000000    10.000000

In [ ]:
house_model.dropna(inplace=True)

In [ ]:
house_model.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [ ]:
house_model.columns

Index(['Posted On', 'BHK', 'Rent', 'Size', 'Floor', 'Area Type',
       'Area Locality', 'City', 'Furnishing Status', 'Tenant Preferred',
       'Bathroom', 'Point of Contact'],
      dtype='object')

In [ ]:
x = house_model.total_rooms

In [ ]:
y = house_model.median_house_value

In [ ]:
x.head()

0    3885.0
1    1510.0
2    3589.0
3      67.0
4    1241.0
Name: total_rooms, dtype: float64

In [ ]:
y.head()

0    344700.0
1    176500.0
2    270500.0
3    330000.0
4     81700.0
Name: median_house_value, dtype: float64

In [ ]:
from scipy.sparse.construct import random
X_train, X_test, y_train, y_test = train_test_split(x,y,train_size=0.7)

In [ ]:
X_train.shape

(2100,)

In [ ]:
X_test.shape

(900,)

In [ ]:
type(X_test)

pandas.core.series.Series

In [ ]:
x_test = X_test.to_numpy(dtype = 'int')
x_train = X_train.to_numpy(dtype = 'int')
y_test = y_test.to_numpy(dtype = 'int')
y_train = y_train.to_numpy(dtype = 'int')

In [ ]:
y_train

array([ 94200, 109400,  66400, ..., 215000, 160300, 160800])

In [ ]:
x_train

array([1510, 2273, 1302, ..., 2837, 1297, 2294])

In [ ]:
def compute_cost(x,y,w,b):
  m = x.shape[0]
  cost = 0

  for i in range(m):
    f_wb = w*x[i]+b
    cost += (f_wb - y[i])**2
  cost = cost*(1/(2*m))
  return cost

In [ ]:
print(compute_cost(x_train,y_train,10,0))

1481865151.5

In [ ]:
def compute_gradient(x,y,w,b):

  m = x.shape[0]
  dj_dw = 0
  dj_db = 0

  for i in range(m):
    f_wb = w*x[i]+b
    dj_dw_i = (f_wb - y[i])*x[i]
    dj_db_i = (f_wb - y[i])

    dj_dw += dj_dw_i
    dj_db += dj_db_i

  dj_dw = dj_dw/m
  dj_db = dj_db/m

  return dj_dw, dj_db

In [ ]:
def gradient_descent(x,y,w_in,b_in,alpha,num_iters, cost_function, gradient_function):
  w = copy.deepcopy(w_in)
  j_history = []
  p_history = []
  b = b_in
  w = w_in

  for i in range(num_iters):
    dj_dw, dj_db = gradient_function(x,y,w,b)

    b = b-alpha*dj_db
    w = w-alpha*dj_dw


    # if i < 10000:
    #   j_history.append(cost_function(x,y,w,b))
    #   p_history.append([w,b])

    # if i%math.ceil(num_iters/10) == 0:
    #   print(f"Iteration {i:4}: Cost {j_history[-1]:0.2e} ",
    #               f"dj_dw: {dj_dw: 0.3e}, dj_db: {dj_db: 0.3e}  ",
    #               f"w: {w: 0.3e}, b:{b: 0.5e}")
      
  return w,b, j_history,p_history

In [ ]:
w_init = 0
b_init = 0

iterations = 10000
tmp_alpha = 1.0e-02
x_train = np.array([300, 8000, 5000])
y_train = np.array([3, 80, 50])
w_final,b_final,j_hist,p_hist = gradient_descent(x_train, y_train, w_init, b_init, tmp_alpha, iterations, compute_cost, compute_gradient)
print(f"(w,b) found by gradient descent: ({w_final:8.4f},{b_final:8.4f})")

(w,b) found by gradient descent: (     nan,     nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in double_scalars
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in double_scalars

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in double_scalars
  if sys.path[0] == '':